server:
  port: 8050
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: account
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/orderingsystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: account-8050
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.snowy.southwind.bean
